import type { InventoryItem } from "@/types/inventory";
import { dummyInventoryItemsCategories } from "./dummyInventoryItemsCategory";

export const dummyInventoryItems: InventoryItem[] = [
  {
    id: 'inv-001',
    name: 'Beras Cianjur',
    description: 'Beras putih premium untuk nasi uduk',
    unit: 'Liter',
    purchase_price: 12000,
    category: dummyInventoryItemsCategories[0],
    quantity: 100,
    threshold: 30,
    expired_date: new Date('2025-07-01T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-002',
    name: 'Santan Kelapa',
    description: 'Santan cair segar untuk memasak nasi uduk',
    unit: 'Saset',
    purchase_price: 7000,
    category: dummyInventoryItemsCategories[0],
    quantity: 50,
    threshold: 20,
    expired_date: new Date('2025-06-10T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-003',
    name: 'Daun Salam',
    description: '',
    unit: 'Lembar',
    purchase_price: 2000,
    category: dummyInventoryItemsCategories[0],
    quantity: 20,
    threshold: 5,
    expired_date: new Date('2025-06-15T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-004',
    name: 'Serai',
    description: '',
    unit: 'pcs',
    purchase_price: 1500,
    category: dummyInventoryItemsCategories[0],
    quantity: 25,
    threshold: 8,
    expired_date: new Date('2025-06-18T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-005',
    name: 'Garam',
    description: '',
    unit: 'Saset',
    purchase_price: 1000,
    category: dummyInventoryItemsCategories[0],
    quantity: 40,
    threshold: 10,
    expired_date: new Date('2025-06-31T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-006',
    name: 'Ayam Potong',
    description: 'Daging ayam untuk goreng atau semur',
    unit: 'pcs',
    purchase_price: 35000,
    category: dummyInventoryItemsCategories[1],
    quantity: 30,
    threshold: 10,
    expired_date: new Date('2025-06-08T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-007',
    name: 'Telur Ayam',
    description: '',
    unit: 'pcs',
    purchase_price: 2000,
    category: dummyInventoryItemsCategories[1],
    quantity: 100,
    threshold: 30,
    expired_date: new Date('2025-06-15T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-008',
    name: 'Tempe',
    description: '',
    unit: 'pcs',
    purchase_price: 5000,
    category: dummyInventoryItemsCategories[1],
    quantity: 60,
    threshold: 15,
    expired_date: new Date('2025-06-09T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-009',
    name: 'Tahu',
    description: '',
    unit: 'pcs',
    purchase_price: 4000,
    category: dummyInventoryItemsCategories[1],
    quantity: 45,
    threshold: 12,
    expired_date: new Date('2025-06-09T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-010',
    name: 'Ikan Asin',
    description: '',
    unit: 'pcs',
    purchase_price: 10000,
    category: dummyInventoryItemsCategories[1],
    quantity: 20,
    threshold: 5,
    expired_date: new Date('2025-06-31T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-011',
    name: 'Bawang Merah Goreng',
    description: '',
    unit: 'Pack',
    purchase_price: 15000,
    category: dummyInventoryItemsCategories[2],
    quantity: 15,
    threshold: 5,
    expired_date: new Date('2025-06-31T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-012',
    name: 'Sambal Kacang',
    description: 'Sambal kacang khas nasi uduk',
    unit: 'Pack',
    purchase_price: 7000,
    category: dummyInventoryItemsCategories[2],
    quantity: 10,
    threshold: 5,
    expired_date: new Date('2025-06-12T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-013',
    name: 'Timun',
    description: '',
    unit: 'pcs',
    purchase_price: 3000,
    category: dummyInventoryItemsCategories[2],
    quantity: 30,
    threshold: 10,
    expired_date: new Date('2025-06-06T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-014',
    name: 'Kerupuk',
    description: '',
    unit: 'pcs',
    purchase_price: 1000,
    category: dummyInventoryItemsCategories[2],
    quantity: 100,
    threshold: 20,
    expired_date: new Date('2025-06-31T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-015',
    name: 'Acar',
    description: '',
    unit: 'pcs',
    purchase_price: 4000,
    category: dummyInventoryItemsCategories[2],
    quantity: 15,
    threshold: 5,
    expired_date: new Date('2025-06-10T00:00:00'),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  // item with new category
  {
    id: 'inv-016',
    name: 'Kertas Struk',
    description: 'Kertas untuk print struk',
    unit: 'box',
    purchase_price: 30000,
    category: dummyInventoryItemsCategories[3],
    quantity: 0,
    threshold: 5,
    expired_date: new Date(),
    meta: { created_at: new Date(), updated_at: new Date() },
  },
  {
    id: 'inv-017',
    name: 'Sabun Cuci Piring',
    description: 'Sabun Sunlight untuk cuci piring',
    unit: 'saset',
    purchase_price: 10000,
    category: dummyInventoryItemsCategories[3],
    quantity: 0,
    threshold: 5,
    expired_date: new Date(),
    meta: { created_at: new Date(), updated_at: new Date() },
  }
];